sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t lakshy/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lakshy/react-test npm test

after_success:
  - docker build -t lakshy/multi-client ./client
  - docker build -t lakshy/multi-nginx ./nginx
  - docker build -t lakshy/multi-server ./server
  - docker build -t lakshy/multi-worker ./worker
  # Login to the CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker build lakshy/multi-client
  - docker build lakshy/multi-nginx
  - docker build lakshy/multi-server
  - docker build lakshy/multi-worker